import pyodbc
import csv

conn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};'
                      'SERVER=localhost;'
                      'DATABASE=TCSWEB;'
                      'TRUSTED_CONNECTION=yes;')

cursor = conn.cursor()

cursor.execute("DROP TABLE TEMPDELIVERY")
cursor.execute('''
    CREATE TABLE TCSWEB.dbo.TEMPDELIVERY (
	MFSTKEY VARCHAR(20) PRIMARY KEY NOT NULL,
    BOLNUM VARCHAR(9) NOT NULL,
    ROUTECODE VARCHAR(9) NOT NULL,
	PRONUM VARCHAR(10) NOT NULL,
	DOORNUM VARCHAR(9) NOT NULL,
	BINNUM VARCHAR(9) NOT NULL,
	ROLLNUM VARCHAR(9) NOT NULL,
    TERMINAL VARCHAR(10) NOT NULL,
    SHIPNAME VARCHAR(30) NOT NULL,
    CONSNAME VARCHAR(30) NOT NULL,
    CONSADD1 VARCHAR(30) NOT NULL,
    CONSADD2 VARCHAR(30) NULL,
    PRODUCTDESC VARCHAR(300) NOT NULL,
    PRODUCTWEIGHT SMALLINT NOT NULL,
    WIDTH SMALLINT NOT NULL,
	HEIGHT SMALLINT NOT NULL
);''')

bol_data = [
    {
        "MFSTKEY": "047X081925001",
        "BOLNUM": "A8G3P9K5Y",
        "ROUTECODE": "E5S8R4W2Z",
        "PRONUM": "12345678",
        "DOORNUM": "A2B3D4F5H",
        "BINNUM": "E5S8R4W2Z",
        "ROLLNUM": "T9Y2U7I4O",
        "TERMINAL": "03",
        "SHIPNAME": "Global Carpets Inc.",
        "CONSNAME": "MOHAWK WHSE/MENDOTA HEIGHTS",
        "CONSADD1": "2359 WATERS DRIVE",
        "CONSADD2": None,
        "PRODUCTDESC": "Carpet Tiles, 2'x2'",
        "PRODUCTWEIGHT": 4500,
        "WIDTH": 48,
        "HEIGHT": 48,
    },
    {
        "MFSTKEY": "047X081925002",
        "BOLNUM": "A8G3P9K5Y",
        "ROUTECODE": "E5S8R4W2Z",
        "PRONUM": "12345678",
        "DOORNUM": "A2B3D4F5H",
        "BINNUM": "E5S8R4W2Z",
        "ROLLNUM": "G7H3J2K1L",
        "TERMINAL": "03",
        "SHIPNAME": "Global Carpets Inc.",
        "CONSNAME": "TORBURG BUILDERS",
        "CONSADD1": "396 33RD AVE S",
        "CONSADD2": None,
        "PRODUCTDESC": "Low Pile Carpet Rolls",
        "PRODUCTWEIGHT": 1200,
        "WIDTH": 144,
        "HEIGHT": 18,
    },
    {
        "MFSTKEY": "047X081925003",
        "BOLNUM": "A8G3P9K5Y",
        "ROUTECODE": "E5S8R4W2Z",
        "PRONUM": "12345678",
        "DOORNUM": "A2B3D4F5H",
        "BINNUM": "E5S8R4W2Z",
        "ROLLNUM": "Q9W8E7R6T",
        "TERMINAL": "03",
        "SHIPNAME": "Global Carpets Inc.",
        "CONSNAME": "LEMONT PARK DISTRICT",
        "CONSADD1": "16028 W 127TH ST",
        "CONSADD2": None,
        "PRODUCTDESC": "Palletized Carpet Tiles",
        "PRODUCTWEIGHT": 3800,
        "WIDTH": 48,
        "HEIGHT": 48,
    },
    {
        "MFSTKEY": "047X081925004",
        "BOLNUM": "A8G3P9K5Y",
        "ROUTECODE": "E5S8R4W2Z",
        "PRONUM": "12345678",
        "DOORNUM": "A2B3D4F5H",
        "BINNUM": "E5S8R4W2Z",
        "ROLLNUM": "Z6X5C4V3B",
        "TERMINAL": "03",
        "SHIPNAME": "Global Carpets Inc.",
        "CONSNAME": "CARPET FAIR INC",
        "CONSADD1": "DBA FLOORING AMERICA",
        "CONSADD2": "2250 W SIBLEY BLVD",
        "PRODUCTDESC": "Extra Large Carpet Rolls",
        "PRODUCTWEIGHT": 2500,
        "WIDTH": 180,
        "HEIGHT": 24,
    },
    {
        "MFSTKEY": "047X081925005",
        "BOLNUM": "L9K2J8H4G",
        "ROUTECODE": "Q8R3T6Y9I",
        "PRONUM": "87654321",
        "DOORNUM": "B4C5E6F7G",
        "BINNUM": "Q8R3T6Y9I",
        "ROLLNUM": "P1O2I3U4Y",
        "TERMINAL": "08",
        "SHIPNAME": "Flooring Solutions LLC",
        "CONSNAME": "CARPET FAIR INC",
        "CONSADD1": "DBA FLOORING AMERICA",
        "CONSADD2": "2250 W SIBLEY BLVD",
        "PRODUCTDESC": "Carpet Tiles, 2'x2'",
        "PRODUCTWEIGHT": 4500,
        "WIDTH": 48,
        "HEIGHT": 48,
    },
    {
        "MFSTKEY": "047X081925006",
        "BOLNUM": "L9K2J8H4G",
        "ROUTECODE": "Q8R3T6Y9I",
        "PRONUM": "87654321",
        "DOORNUM": "B4C5E6F7G",
        "BINNUM": "Q8R3T6Y9I",
        "ROLLNUM": "A1S2D3F4G",
        "TERMINAL": "08",
        "SHIPNAME": "Flooring Solutions LLC",
        "CONSNAME": "DESIGNS BY NICOLETTE",
        "CONSADD1": "10800 CENTRAL AVE",
        "CONSADD2": None,
        "PRODUCTDESC": "Low Pile Carpet Rolls",
        "PRODUCTWEIGHT": 1200,
        "WIDTH": 144,
        "HEIGHT": 18,
    },
    {
        "MFSTKEY": "047X081925007",
        "BOLNUM": "L9K2J8H4G",
        "ROUTECODE": "Q8R3T6Y9I",
        "PRONUM": "87654321",
        "DOORNUM": "B4C5E6F7G",
        "BINNUM": "Q8R3T6Y9I",
        "ROLLNUM": "Z9X8C7V6B",
        "TERMINAL": "08",
        "SHIPNAME": "Flooring Solutions LLC",
        "CONSNAME": "S & M CARPETS",
        "CONSADD1": "DBA ROYAL HOME FLOORING",
        "CONSADD2": "7509 WEST 85TH STREET",
        "PRODUCTDESC": "Palletized Carpet Tiles",
        "PRODUCTWEIGHT": 3800,
        "WIDTH": 48,
        "HEIGHT": 48,
    },
    {
        "MFSTKEY": "047X081925008",
        "BOLNUM": "L9K2J8H4G",
        "ROUTECODE": "Q8R3T6Y9I",
        "PRONUM": "87654321",
        "DOORNUM": "B4C5E6F7G",
        "BINNUM": "Q8R3T6Y9I",
        "ROLLNUM": "B8N7M6L5K",
        "TERMINAL": "08",
        "SHIPNAME": "Flooring Solutions LLC",
        "CONSNAME": "HOMES ELEM SCHOOL",
        "CONSADD1": "508 N KENILWORH AVE",
        "CONSADD2": None,
        "PRODUCTDESC": "Extra Large Carpet Rolls",
        "PRODUCTWEIGHT": 2500,
        "WIDTH": 180,
        "HEIGHT": 24,
    },
    {
        "MFSTKEY": "047X081925009",
        "BOLNUM": "M5N4B3V2C",
        "ROUTECODE": "Z1A2B3C4D",
        "PRONUM": "98765432",
        "DOORNUM": "C6D7E8F9A",
        "BINNUM": "Z1A2B3C4D",
        "ROLLNUM": "R1T2Y3U4I",
        "TERMINAL": "15",
        "SHIPNAME": "Master Flooring Group",
        "CONSNAME": "EAGLE CARPET SERVICES LTD",
        "CONSADD1": "135 S FAIRBANK STREET",
        "CONSADD2": None,
        "PRODUCTDESC": "Carpet Tiles, 2'x2'",
        "PRODUCTWEIGHT": 4500,
        "WIDTH": 48,
        "HEIGHT": 48,
    },
    {
        "MFSTKEY": "047X081925010",
        "BOLNUM": "M5N4B3V2C",
        "ROUTECODE": "Z1A2B3C4D",
        "PRONUM": "98765432",
        "DOORNUM": "C6D7E8F9A",
        "BINNUM": "Z1A2B3C4D",
        "ROLLNUM": "F5G6H7J8K",
        "TERMINAL": "15",
        "SHIPNAME": "Master Flooring Group",
        "CONSNAME": "EAGLE CARPET SERVICES LTD",
        "CONSADD1": "135 S FAIRBANK STREET",
        "CONSADD2": None,
        "PRODUCTDESC": "Low Pile Carpet Rolls",
        "PRODUCTWEIGHT": 1200,
        "WIDTH": 144,
        "HEIGHT": 18,
    },
    {
        "MFSTKEY": "047X081925011",
        "BOLNUM": "T1U2V3W4X",
        "ROUTECODE": "X9C8V7B6N",
        "PRONUM": "23456789",
        "DOORNUM": "D1E2F3G4H",
        "BINNUM": "X9C8V7B6N",
        "ROLLNUM": "L1K2J3H4G",
        "TERMINAL": "22",
        "SHIPNAME": "Carpet Kings LLC",
        "CONSNAME": "EAGLE CARPET SERVICES LTD",
        "CONSADD1": "135 S FAIRBANK STREET",
        "CONSADD2": None,
        "PRODUCTDESC": "Carpet Tiles, 2'x2'",
        "PRODUCTWEIGHT": 4500,
        "WIDTH": 48,
        "HEIGHT": 48,
    },
    {
        "MFSTKEY": "047X081925012",
        "BOLNUM": "P7O6I5U4Y",
        "ROUTECODE": "B7N6M5L4K",
        "PRONUM": "34567890",
        "DOORNUM": "E2F3G4H5I",
        "BINNUM": "B7N6M5L4K",
        "ROLLNUM": "S1D2F3G4H",
        "TERMINAL": "29",
        "SHIPNAME": "The Rug & Roll Co.",
        "CONSNAME": "GORMANS HOSPITALITY SOLUTIONS",
        "CONSADD1": "200 COVINGTON DR",
        "CONSADD2": None,
        "PRODUCTDESC": "Low Pile Carpet Rolls",
        "PRODUCTWEIGHT": 1200,
        "WIDTH": 144,
        "HEIGHT": 18,
    },
    {
        "MFSTKEY": "047X081925013",
        "BOLNUM": "C9D8E7F6G",
        "ROUTECODE": "V5C4X3Z2A",
        "PRONUM": "45678901",
        "DOORNUM": "F3G4H5I6J",
        "BINNUM": "V5C4X3Z2A",
        "ROLLNUM": "P1O2I3U4Y",
        "TERMINAL": "03",
        "SHIPNAME": "Global Carpets Inc.",
        "CONSNAME": "PERFORMERS CARPET & TILE",
        "CONSADD1": "25 W 561 ARMY TRAIL ROAD",
        "CONSADD2": None,
        "PRODUCTDESC": "Palletized Carpet Tiles",
        "PRODUCTWEIGHT": 3800,
        "WIDTH": 48,
        "HEIGHT": 48,
    },
]

# Example of how to iterate and insert the data
# You'll need to adapt this to your specific database connection and cursor
for record in bol_data:
    query = """
        INSERT INTO TCSWEB.dbo.TEMPDELIVERY (
        MFSTKEY, BOLNUM, ROUTECODE, PRONUM, DOORNUM, BINNUM, ROLLNUM, TERMINAL, SHIPNAME, 
        CONSNAME, CONSADD1, CONSADD2, PRODUCTDESC, PRODUCTWEIGHT, WIDTH, HEIGHT
        )
        VALUES (
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
        );"""
    
    params = (
        record["MFSTKEY"],
        record["BOLNUM"],
        record["ROUTECODE"],
        record["PRONUM"],
        record["DOORNUM"],
        record["BINNUM"],
        record["ROLLNUM"],
        record["TERMINAL"],
        record["SHIPNAME"],
        record["CONSNAME"],
        record["CONSADD1"],
        record["CONSADD2"],
        record["PRODUCTDESC"],
        record["PRODUCTWEIGHT"],
        record["WIDTH"],
        record["HEIGHT"],
    )

    cursor.execute(query, params)

conn.commit()
conn.close()